Java_Exception_Propagation
-----------------------------
=> An exception is first thrown from the top of the stack and if it is not caught, 
   it drops down the call stack to the previous method. If not caught there, 
   the exception again drops down to the previous method, and so on until they are caught or until they reach the very bottom of the call stack. 
   This is called exception propagation


✍ Note: By default Unchecked Exceptions are forwarded in calling chain (propagated).
--------

=> Exception Propagation Example 1
----------------------------------
		TestExceptionPropagation1.java
		
			class TestExceptionPropagation1
			{  
			  	void m()
			  	{  
			    	int data=50/0;  
			  	}  
			  	void n()
			  	{  
			    	m();  
			 	}  
			  	void p()
			  	{  
			   		try
			   		{  
			    		n();  
				   	}catch(Exception e)
			   		{
			   			System.out.println("exception handled");
			   		}  
				}  
			
				public static void main(String args[])
				{  
				   TestExceptionPropagation1 obj=new TestExceptionPropagation1();  
				   obj.p();  
				   System.out.println("normal flow...");  
				}  
			}  
		
				
⦿	Exception can be handled in any method in call stack either in the main() method, p() method, n() method or m() method.
		==========================================================================
			Go in Phothos Folder and see multiple-catch-block-in-java.png
		==========================================================================


✍ Note: By default, Checked Exceptions are not forwarded in calling chain (propagated).
------- 	
	
=> Exception Propagation Example
----------------------------------
		TestExceptionPropagation2.java
		
			class TestExceptionPropagation2
			{  
				  void m()
				  {  
				  	  throw new java.io.IOException("device error");//checked exception  
				  }  
				  void n()
				  {  
				  	  m();  
				  }  
				  void p()
				  {  
				  	 try
				  	 {  
				    	n();  
				   	 }catch(Exception e)
				   	 {
				   	 	System.out.println("exception handeled");
				   	 }  
				  }  
				  public static void main(String args[])
				  {  
					   TestExceptionPropagation2 obj=new TestExceptionPropagation2();  
					   obj.p();  
					   System.out.println("normal flow");  
				  }  
			}  